### ISSUE TITLE
Performance CodecZstd vs CodecZlib

### ISSUE THREAD

**Issue by Ankur-deDev** [JuliaIO/CodecZstd.jl#17]
Hi,

I am trying to compare `ZstdDecompressorStream`  with `GzipDecompressorStream`.
Let's consider a dataframe with two random float columns, compressed using zstd and gzip.

> 973M stats.csv
> 423M stats.csv.gz
> 448M stats.csv.zst

ZStd uncompress faster:

- 5.519s for `time zcat stats.csv.gz > /dev/null`

- 1.754s for `time zstdcat stats.csv.zst > /dev/null`

In Julia, I use the following to load the dataframe (taken from [here](https://stackoverflow.com/questions/52590792/how-do-i-read-a-gzipped-csv-file-in-julia)):

```
using CodecZstd, CodecZlib, CSVFiles, DataFrames, FileIO

function loader(file_name, decompressor)
  open(file_name) do io
    load(Stream(format"CSV", decompressor(io))) |> DataFrame
  end
end
```

With that code, I consistently get the following results:
```
julia> @time DataFrame(load("stats.csv"));
  2.425661 seconds (534 allocations: 1.002 GiB, 3.74% gc time)

julia> @time loader("stats.csv.gz", GzipDecompressorStream);
 10.230154 seconds (249.48 k allocations: 2.082 GiB, 1.71% gc time)

julia> @time loader("stats.csv.zst", ZstdDecompressorStream);
 16.919650 seconds (62.90 k allocations: 2.079 GiB, 1.15% gc time)

```
I am surprised to see that `ZstdDecompressorStream` is slower despite the gains seen above in decompression.

Are those results expected for the following versions of the packages?
```
(v1.1) pkg> st
    Status `~/.julia/environments/v1.1/Project.toml`
  [5d742f6a] CSVFiles v0.15.0
  [944b1d66] CodecZlib v0.6.0
  [6b39b394] CodecZstd v0.6.1
  [a93c6f00] DataFrames v0.19.2
  [5789e2e9] FileIO v1.0.7
```
```
julia> versioninfo()
Julia Version 1.1.1
Commit 55e36cc308 (2019-05-16 04:10 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, skylake)
```

**Comment by bicycle1885** [comment]
I can reproduce the slowdown. Thank you for reporting it.

I quickly investigated it and found the latest version of CodecZstd.jl (i.e., v0.6.1) is particularly slow. Can you try v0.6.0? The only difference is zstd binaries and its installation script. In my machine, the performance degradation went away.

**Comment by Ankur-deDev** [comment]
Thanks for your quick answer.
I could confirm that the performance are inline with expectations, using v0.6.0 I got:
```
julia> @time loader("stats.csv.zst", ZstdDecompressorStream);
  5.098420 seconds (62.90 k allocations: 2.079 GiB, 5.03% gc time)
```

**Comment by bicycle1885** [comment]
I'd rather keep this issue open until I resolve the problem so that other people (including me) can easily find it.
